### PR TITLE
Standardize identifiers

### PR DESCRIPTION
**Pull request by nordlow**

### CODE REVIEW

**Comment by nordlow** [comment]
Ready for merge now. `./run_tests.sh` pass locally.

**Comment by nordlow** [comment]
I don't see any CI jobs.

**Comment by nordlow** [comment]
I strongly advice you to adjust your code so no errors are triggered by sanitiizers. 

Next up is:

```
./run_tests_with_gcc_sanitizers.sh 
parser/metac_parser.c:2760:22: runtime error: store to misaligned address 0x7f80b9a5da24 for type 'struct decl_parameter_t *', which requires 8 byte alignment
0x7f80b9a5da24: note: pointer points here
  80 7f 00 00 00 00 00 00  00 00 00 00 00 00 00 00  be be be be be be be be  be be be be 68 00 00 00
```

.

Update: I disabled alignment sanitizing via `-fno-sanitize=alignment` for now.

**Comment by UplinkCoder** [comment]
yeah the alignment constraints are a problem. 
In theory, but not in practice.

I am going to squash your PR into one commit and merge it as a whole.

**Comment by nordlow** [comment]
Thanks for approving!

**Pull request merged**
